### ISSUE TITLE
Cannot compile; use option -std=c99 or -std=gnu99 

### ISSUE THREAD

**Issue by probonopd** [Agorise/c-ipfs#16]
Cannot compile; use option `-std=c99` or `-std=gnu99` but how?

```
gcc -c -o cid.o cid.c -O0 -I../include -I../c-libp2p/include -I../c-libp2p/c-multihash/include -I../c-libp2p/c-multiaddr/include -I../c-libp2p/c-protobuf -Wall -g3
cid.c: In function ‘ipfs_cid_compare’:
cid.c:336:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for(size_t i = 0; i < a->hash_length; i++) {
  ^
cid.c:336:2: note: use option -std=c99 or -std=gnu99 to compile your code
make[1]: *** [cid.o] Error 1
make[1]: Leaving directory `/home/travis/build/probonopd/c-ipfs/cid'
make: *** [all] Error 2
```

Build log:
https://travis-ci.com/probonopd/c-ipfs/builds/96092843#L925-L934

Build script:
https://github.com/probonopd/c-ipfs/blob/patch-1/.travis.yml

**Comment by marcialvieira** [comment]
Thank you for reporting, fixed, do the same in your fork.
https://github.com/Agorise/c-ipfs/commit/bdcb4a2ef601277eeda0d58bb9a6b24be680f2c2

**Comment by probonopd** [comment]
Thanks, now failing a bit further down below:

https://travis-ci.com/probonopd/c-ipfs/builds/96094780#L937

**Comment by marcialvieira** [comment]
Updated a lot now, I think should fix it all.

**Comment by probonopd** [comment]
Now getting `unknown type name ‘u_char’`, could it need `-std=gnu11`?

**Comment by marcialvieira** [comment]
No, I had the same problem compiling for OpenWrt, need to `#include <sys/types.h>`

**Comment by marcialvieira** [comment]
Updated, thank you for reminding me.
https://github.com/Agorise/c-ipfs/commit/87ff29736c451fd815bf575185ffc60e6cb39848#diff-f5bba7172550a6be5b237fa6277b4307R49

**Comment by probonopd** [comment]
Thanks for your help, still getting

```
/usr/include/arpa/nameser.h:115:2: error: unknown type name ‘u_char’
  const u_char *_msg, *_eom;
```

https://travis-ci.com/probonopd/c-ipfs/builds/96097664#L1050

**Comment by marcialvieira** [comment]
I don't think it is necessary, but I define _BSD_SOURCE just in case.
https://github.com/Agorise/c-ipfs/commit/eb0746794a6a643a7a19a2a94299c90a42d737ff#diff-f5bba7172550a6be5b237fa6277b4307R49

**Comment by probonopd** [comment]
Sorry to be a pain, but I don't know what it is this time...

https://travis-ci.com/probonopd/c-ipfs/builds/96107310

**Comment by marcialvieira** [comment]
Still u_char, but a lot of errors now, I'll try testing your build script here before posting any changes.

**Comment by marcialvieira** [comment]
It should work now, at least I tested it on a trusty container using the same packages that you installed using your travis script.
